Repository Ormi-Trillion/AILearn, pull requests merged in 2024-09, with the labels that each got.

#91 71/comment api 테스트 및 수정
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/CommentsController.java
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/PostController.java
  src/main/java/com/example/ormi5finalteam1/domain/comment/Comment.java
  src/main/java/com/example/ormi5finalteam1/domain/comment/dto/CommentDto.java
  src/main/java/com/example/ormi5finalteam1/domain/comments/Comments.java
  src/main/java/com/example/ormi5finalteam1/domain/comments/dto/CommentsDto.java
  src/main/java/com/example/ormi5finalteam1/repository/CommentRepository.java
  src/main/java/com/example/ormi5finalteam1/service/CommentService.java
  src/main/java/com/example/ormi5finalteam1/service/PostService.java
  src/main/java/com/example/ormi5finalteam1/service/UserPostService.java
Labels: qa

#94 fix(Post): pagination/soft-delete 구현
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/PostController.java
  src/main/java/com/example/ormi5finalteam1/domain/post/Post.java
  src/main/java/com/example/ormi5finalteam1/repository/PostRepository.java
  src/main/java/com/example/ormi5finalteam1/service/PostService.java
Labels: enhancement

#116 test(tests): Test 도메인 관련 테스트 코드 작성
  src/main/java/com/example/ormi5finalteam1/domain/test/SubmitRequestDto.java
  src/main/java/com/example/ormi5finalteam1/domain/test/SubmitRequestVo.java
  src/main/java/com/example/ormi5finalteam1/domain/user/User.java
  src/main/java/com/example/ormi5finalteam1/service/TestService.java
  src/test/java/com/example/ormi5finalteam1/controller/rest_controller/TestControllerTest.java
  src/test/java/com/example/ormi5finalteam1/entity/TestTest.java
  src/test/java/com/example/ormi5finalteam1/repository/TestRepositoryTest.java
  src/test/java/com/example/ormi5finalteam1/service/TestServiceTest.java
Labels: qa

#150 feat(tests): 테스트 관련 html, css 작성
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/TestController.java
  src/main/java/com/example/ormi5finalteam1/controller/thymeleaf_controller/TestInfoController.java
  src/main/java/com/example/ormi5finalteam1/domain/Grade.java
  src/main/java/com/example/ormi5finalteam1/domain/test/TestResultResponseDto.java
  src/main/java/com/example/ormi5finalteam1/security/SecurityConfig.java
  src/main/java/com/example/ormi5finalteam1/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/example/ormi5finalteam1/service/TestService.java
  src/main/resources/static/css/level-test.css
  src/main/resources/static/css/select-level.css
  src/main/resources/static/css/test-result.css
  src/main/resources/static/js/tests.js
  src/main/resources/templates/tests/level-test.html
  src/main/resources/templates/tests/select-level.html
  src/main/resources/templates/tests/test-result.html
  src/main/resources/templates/tests/upgrade-test.html
  src/test/java/com/example/ormi5finalteam1/controller/rest_controller/TestControllerTest.java
  src/test/java/com/example/ormi5finalteam1/service/TestServiceTest.java
Labels: enhancement

#156 154/게시글 키워드 조회 기능 추가
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/PostController.java
  src/main/java/com/example/ormi5finalteam1/repository/PostRepository.java
  src/main/java/com/example/ormi5finalteam1/service/CommentService.java
  src/main/java/com/example/ormi5finalteam1/service/PostService.java
  src/main/resources/http/comment.http
  src/main/resources/http/post.http
Labels: enhancement

#158 feat(admin): 관리자 - 사용자 비활성화, 계정 삭제, 게시글 삭제, 댓글 삭제 구현
  src/main/java/com/example/ormi5finalteam1/common/exception/ErrorCode.java
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/AdminController.java
  src/main/java/com/example/ormi5finalteam1/domain/user/User.java
  src/main/java/com/example/ormi5finalteam1/repository/CommentRepository.java
  src/main/java/com/example/ormi5finalteam1/service/AdminService.java
  src/main/java/com/example/ormi5finalteam1/service/CommentService.java
Labels: enhancement

#160 fix(admin): getPostById -> getPost 변경
  src/main/java/com/example/ormi5finalteam1/service/AdminService.java
Labels: enhancement

#166 157/post 단위 테스트
  src/test/java/com/example/ormi5finalteam1/controller/rest_controller/PostControllerTest.java
  src/test/java/com/example/ormi5finalteam1/repository/PostRepositoryTest.java
  src/test/java/com/example/ormi5finalteam1/service/PostServiceTest.java
Labels: qa

#174 173/like api 구현
  src/main/java/com/example/ormi5finalteam1/common/exception/ErrorCode.java
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/LikeController.java
  src/main/java/com/example/ormi5finalteam1/domain/like/Like.java
  src/main/java/com/example/ormi5finalteam1/domain/like/dto/LikeDto.java
  src/main/java/com/example/ormi5finalteam1/repository/LikeRepository.java
  src/main/java/com/example/ormi5finalteam1/service/LikeService.java
  src/main/resources/http/like.http
  src/test/java/com/example/ormi5finalteam1/controller/rest_controller/LikeControllerTest.java
  src/test/java/com/example/ormi5finalteam1/repository/LikeRepositoryTest.java
  src/test/java/com/example/ormi5finalteam1/service/LikeServiceTest.java
Labels: enhancement, qa

#180 fix(Post): 조회수 카운트 기능 추가
  src/main/java/com/example/ormi5finalteam1/domain/post/Post.java
  src/main/java/com/example/ormi5finalteam1/service/PostService.java
Labels: enhancement

#186 185/admin remain api
  src/main/java/com/example/ormi5finalteam1/common/exception/ErrorCode.java
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/AdminController.java
  src/main/java/com/example/ormi5finalteam1/domain/comment/dto/AdminCommentDto.java
  src/main/java/com/example/ormi5finalteam1/domain/post/dto/AdminPostDetailDto.java
  src/main/java/com/example/ormi5finalteam1/domain/post/dto/AdminPostListDto.java
  src/main/java/com/example/ormi5finalteam1/domain/user/dto/UserInfoDto.java
  src/main/java/com/example/ormi5finalteam1/repository/UserRepository.java
  src/main/java/com/example/ormi5finalteam1/service/AdminService.java
  src/main/java/com/example/ormi5finalteam1/service/PostService.java
Labels: enhancement

#218 test(Comment): 단위테스트 오류 수정
  src/test/java/com/example/ormi5finalteam1/controller/rest_controller/CommentControllerTest.java
  src/test/java/com/example/ormi5finalteam1/service/CommentServiceTest.java
Labels: bug

#231 203/admin api ajax
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/AdminController.java
  src/main/java/com/example/ormi5finalteam1/controller/thymeleaf_controller/AdminInfoController.java
  src/main/java/com/example/ormi5finalteam1/domain/post/dto/AdminPostDetailDto.java
  src/main/java/com/example/ormi5finalteam1/domain/user/dto/UserInfoDto.java
  src/main/java/com/example/ormi5finalteam1/repository/CommentRepository.java
  src/main/java/com/example/ormi5finalteam1/repository/PostRepository.java
  src/main/java/com/example/ormi5finalteam1/repository/UserRepository.java
  src/main/java/com/example/ormi5finalteam1/service/AdminService.java
  src/main/java/com/example/ormi5finalteam1/service/CommentService.java
  src/main/java/com/example/ormi5finalteam1/service/PostService.java
  src/main/resources/static/css/admin-post-detail.css
  src/main/resources/static/css/admin-post-list.css
  src/main/resources/static/css/user-list.css
  src/main/resources/static/js/admin/post-detail.js
  src/main/resources/static/js/admin/post-list.js
  src/main/resources/static/js/admin/user-list.js
  src/main/resources/templates/admin/admin-post-detail.html
  src/main/resources/templates/admin/admin-post-list.html
  src/main/resources/templates/admin/user-list.html
Labels: enhancement

#233 fix(Post): 게시글 상세 조회에서 줄바꿈 안되는 문제 수정
  src/main/resources/static/js/posts/detail.js
Labels: bug

#235 fix(admin): 관리자 게시글 상세 조회 줄바꿈 추가
  src/main/resources/static/js/admin/post-detail.js
Labels: bug

#253 fix(admin, tests): 검색 기능 추가, css 수정
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/AdminController.java
  src/main/java/com/example/ormi5finalteam1/controller/thymeleaf_controller/TestInfoController.java
  src/main/java/com/example/ormi5finalteam1/repository/UserRepository.java
  src/main/java/com/example/ormi5finalteam1/service/AdminService.java
  src/main/java/com/example/ormi5finalteam1/service/TestService.java
  src/main/resources/static/css/admin-post-detail.css
  src/main/resources/static/css/admin-post-list.css
  src/main/resources/static/css/level-test.css
  src/main/resources/static/css/select-level.css
  src/main/resources/static/css/user-list.css
  src/main/resources/static/js/admin/post-detail.js
  src/main/resources/static/js/admin/post-list.js
  src/main/resources/static/js/admin/user-list.js
  src/main/resources/static/js/tests.js
  src/main/resources/templates/admin/admin-post-detail.html
  src/main/resources/templates/admin/admin-post-list.html
  src/main/resources/templates/admin/user-list.html
  src/main/resources/templates/tests/level-test.html
  src/main/resources/templates/tests/select-level.html
  src/main/resources/templates/tests/test-result.html
  src/main/resources/templates/tests/upgrade-test.html
  src/test/java/com/example/ormi5finalteam1/controller/rest_controller/TestControllerTest.java
  src/test/java/com/example/ormi5finalteam1/service/TestServiceTest.java
Labels: bug

#258 feat(admin, tests): 서버 예외 발생시의 에러 페이지 생성
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/AdminController.java
  src/main/java/com/example/ormi5finalteam1/controller/rest_controller/TestController.java
  src/main/java/com/example/ormi5finalteam1/controller/thymeleaf_controller/AdminInfoController.java
  src/main/java/com/example/ormi5finalteam1/controller/thymeleaf_controller/TestInfoController.java
  src/main/java/com/example/ormi5finalteam1/service/AdminService.java
  src/main/java/com/example/ormi5finalteam1/service/TestService.java
  src/main/resources/static/css/error.css
  src/main/resources/static/js/tests.js
  src/main/resources/templates/tests/error.html
Labels: bug

#265 260/fix tests header
  src/main/java/com/example/ormi5finalteam1/security/SecurityConfig.java
  src/main/java/com/example/ormi5finalteam1/service/PostService.java
  src/main/resources/static/css/error.css
  src/main/resources/static/css/test-result.css
  src/main/resources/static/js/admin/post-list.js
  src/main/resources/static/js/tests.js
  src/main/resources/templates/admin/admin-post-detail.html
  src/main/resources/templates/admin/admin-post-list.html
  src/main/resources/templates/admin/user-list.html
  src/main/resources/templates/tests/error.html
  src/main/resources/templates/tests/level-test.html
  src/main/resources/templates/tests/select-level.html
  src/main/resources/templates/tests/test-result.html
  src/test/java/com/example/ormi5finalteam1/controller/rest_controller/TestControllerTest.java
  src/test/resources/application.yml
  src/test/resources/sample.sql
Labels: bug

#272 fix(tests): TestControllerTest 에러 수정
  src/test/java/com/example/ormi5finalteam1/controller/rest_controller/TestControllerTest.java
Labels: bug

#276 style(tests): 테스트 결과 페이지 수정
  src/main/java/com/example/ormi5finalteam1/controller/thymeleaf_controller/TestInfoController.java
  src/main/resources/static/css/level-test.css
  src/main/resources/static/css/select-level.css
  src/main/resources/templates/tests/test-result.html
Labels: qa
